name: Pack ANZTestSolution_v1_0_0_1

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Structure
        shell: pwsh
        run: |
          Write-Host "Current Directory:"
          Get-Location

          Write-Host "Repository Files:"
          Get-ChildItem -Path . -Recurse

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Update Solution Version
        shell: pwsh
        run: |
   
