name: Pack ANZTestSolution

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Structure
        shell: pwsh
        run: |
          Write-Host "Current Directory:"
          Get-Location

          Write-Host "Repository Files:"
          Get-ChildItem -Path . -Recurse

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-folder: contents
          solution-file: main/ANZTestSolution.zip
          solution-type: Both

      - name: Upload Solution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NTTDataSolution
          path: |
            main/NTTDataSolution.zip
            main/NTTDataSolution_managed.zip
